#!/bin/bash

cd /g/data/w35/mm3972/scripts/process_data/make_LIS_landinfo/regrid_DLCD_run
qsub submit_ncl_lat-10.sh
qsub submit_ncl_lat-11.sh
qsub submit_ncl_lat-12.sh
qsub submit_ncl_lat-13.sh
qsub submit_ncl_lat-14.sh
qsub submit_ncl_lat-15.sh
qsub submit_ncl_lat-16.sh
qsub submit_ncl_lat-17.sh
qsub submit_ncl_lat-18.sh
qsub submit_ncl_lat-19.sh
qsub submit_ncl_lat-20.sh
qsub submit_ncl_lat-21.sh
qsub submit_ncl_lat-22.sh
qsub submit_ncl_lat-23.sh
qsub submit_ncl_lat-24.sh
qsub submit_ncl_lat-25.sh
qsub submit_ncl_lat-26.sh
qsub submit_ncl_lat-27.sh
qsub submit_ncl_lat-28.sh
qsub submit_ncl_lat-29.sh
qsub submit_ncl_lat-30.sh
qsub submit_ncl_lat-31.sh
qsub submit_ncl_lat-32.sh
qsub submit_ncl_lat-33.sh
qsub submit_ncl_lat-34.sh
qsub submit_ncl_lat-35.sh
qsub submit_ncl_lat-36.sh
qsub submit_ncl_lat-37.sh
qsub submit_ncl_lat-38.sh
qsub submit_ncl_lat-39.sh
qsub submit_ncl_lat-40.sh
qsub submit_ncl_lat-41.sh
qsub submit_ncl_lat-42.sh
qsub submit_ncl_lat-43.sh
qsub submit_ncl_lat-44.sh